version: "2"

services:
  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${SS_DATABASE_NAME}
      MYSQL_USER: ${SS_DATABASE_USERNAME}
      MYSQL_PASSWORD: ${SS_DATABASE_PASSWORD}
      VIRTUAL_HOST: ${DB_VIRTUAL_HOST}
  ss:
    build: https://github.com/fspringveldt/ss-dockerfile.git
    container_name: ss-site
    links:
      - db
    depends_on:
      - db
    working_dir: /var/www/html/
    volumes:
      - ./:/var/www/
      - ${PROJECT_PATH}:/var/www/html
    environment:
      - VIRTUAL_HOST=${SS_VIRTUAL_HOST}
      - SS_DATABASE_SERVER=db
      - XDEBUG_CONFIG=remote_host=${XDEBUG_REMOTE_HOST}
      - SS_DATABASE_NAME=${SS_DATABASE_NAME}
      - SS_DATABASE_USERNAME=${SS_DATABASE_USERNAME}
      - SS_DATABASE_PASSWORD=${SS_DATABASE_PASSWORD}
      - SS_DEFAULT_ADMIN_USERNAME=${SS_DEFAULT_ADMIN_USERNAME}
      - SS_DEFAULT_ADMIN_PASSWORD=${SS_DEFAULT_ADMIN_PASSWORD}
      - SS_ENVIRONMENT_TYPE=${SS_ENVIRONMENT_TYPE}
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-proxy.conf:/etc/nginx/conf.d/nginx-proxy.conf
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - db:mysql
    depends_on:
      - db
    ports:
      - "8181:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      VIRTUAL_HOST: ${PMA_VIRTUAL_HOST}
volumes:
  db-data:
